apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp2
  labels:
    app: wp2
  namespace: namespace-workflow-1685326654281
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wp2
  template:
    metadata:
      labels:
        app: wp2
    spec:
      containers:
        - name: wp2
          image: akstestcr011.azurecr.io/image-workflow-1685326654281:latest
          ports:
            - containerPort: 3000