apiVersion: v1
kind: Service
metadata:
  name: wp2
  namespace: namespace-workflow-1685326654281
spec:
  type: LoadBalancer
  selector:
    app: wp2
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000